version: "3.9"

x-services-volume: &services-volume
  type: bind
  source: ./src
  target: /home/swift

services:
  swift:
    build:
       context: .
       dockerfile: "./docker/swift/Dockerfile"
    image: ${PROJECT_NAME}_playground:${ENVIRONMENT}-${ENVIRONMENT_VERSION}
    container_name: ${PROJECT_NAME}_playground
    volumes:
      - *services-volume
